services:
  api:
    build:
      context: metrics-api
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/metrics
      - USE_DOCKERIZED_POSTGRES=1
    depends_on:
      - db

  sensors:
    build:
      context: sensors
      dockerfile: Dockerfile
    environment:
      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/metrics
      - USE_DOCKERIZED_POSTGRES=1
    depends_on:
      - db

#  rbi:
#    build:
#      context: rbi
#      dockerfile: Dockerfile
#    devices:
#      - /dev/kfd
#      - /dev/dri
#    security_opt:
#      - seccomp:unconfined
#    group_add:
#      - video
#      - render
#    environment:
#      - POSTGRES_CONNECTION_STRING=postgresql://postgres:postgres@db:5432/metrics
#      - USE_DOCKERIZED_POSTGRES=1
#    depends_on:
#      - db

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: metrics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: